### ISSUE TITLE
3d object rotating over the poles

### ISSUE THREAD

**Issue by walterkonnerth** [glob3mobile/g3m#102] opened 2015-04-14 12:51 UTC
Hi,

I noticed that the 3d object is rotating for 180 degrees when simulating a trajectory over the poles.
How can I avoid it?

**Comment by DiegoGomezDeck** [comment] 2015-04-15 14:51
Hello @walterkonnerth 

Can you show the code that produces this behavior?

**Comment by walterkonnerth** [comment] 2015-04-16 04:42
Hi,
I have a 3d object from a JSON. I made a periodical task and in its run method I calculate its position and display it then on the globe:

```
            3dObject.setScale(10000)
            3dObject.setPitch(AngleWrapper.fromDegrees(270));
            3dObject.setHeading(AngleWrapper.fromDegrees(0));
```

 3dObject.setPosition(
                Geodetic3DWrapper(
                    latitude: AngleWrapper.fromDegrees(_latitude),
                    andLongitude: AngleWrapper.fromDegrees(_longitude),
                    andHeight: _altitude))

I made some wrappers because I am programming in Swift.
When the _latitude is > 70 (near the North Pole) the object is beginning to rotate, the object is facing towards the middle of the North Pole.
What formula do I have to use for the heading near the poles so the heading will not change?

**Comment by DiegoGomezDeck** [comment] 2015-04-24 14:40
Hi @walterkonnerth 

I don't think I follow you.

Do you mean that heading=0 makes the Shape always face to the north? If yes, it's the intended behavior, see: http://en.wikipedia.org/wiki/Course_%28navigation%29#Aircraft_heading

**Comment by DiegoGomezDeck** [comment] 2015-05-25 14:26
Hi @walterkonnerth, did you solve your problem? Can I close this issue?

**Comment by walterkonnerth** [comment] 2015-05-27 04:43
Hi Gomez,

You can close the issue.  I was not familiar with the plane orientation
above the Earth but I read about it and managed to solve the problem.

Regards,

Walter

**Closed as completed** 2015-05-27 13:38 UTC
